name: release

on:
  create:
    tags: ['v*']
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'

      - name: Compute artifact names
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          BASE=wotstat.training-bot_$VERSION
          WOTMOD=${BASE}.wotmod
          MTMOD=${BASE}.mtmod
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "WOTMOD=$WOTMOD" >> $GITHUB_ENV
          echo "MTMOD=$MTMOD" >> $GITHUB_ENV

      - name: build
        run: ./build.sh -v $VERSION && echo Mod name $MOD
        shell: bash

      - name: Archive .wotmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WOTMOD }}
          path: ${{ env.WOTMOD }}

      - name: Archive .mtmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MTMOD }}
          path: ${{ env.MTMOD }}

      - name: upload linux artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: true
          token: ${{ github.token }}
          files: |
            ${{ env.WOTMOD }}
            ${{ env.MTMOD }}
          body: |
            - Prepare for release
